### ISSUE TITLE
5wd3 讨论 BP 项目

### ISSUE THREAD

**Issue by iamzhuoxuan** [iamzhuoxuan/WriterBP#1]
`171127 更新：` 为方便大家一目了然清楚 Issue 截止时间，Nwdn 表示该 Issue 最迟回复时间，与课程组设定的用法相同，例如 5wd3 表示本周三，6wd4 表示下周四。

~ 大家可以在这里先回复自己的项目想法

请大家本周三 22:00 前在此回复 3 个 Idea  ；）

**Comment by sumin1123** [comment]
## 365拍摄计划
* 我姥姥每年会给自己拍一张一寸大头照，从年轻的时候就开始了，一直坚持着。一次她把这些小照片，排成一排，让我们从头到尾看过去，内心的感受无法形容。
* 后来，焦波的《俺爹俺娘》系列、我的摄影老师的拍摄家人计划也影响到我。
* 2017年，为家人、为自己每天拍一张照片，是为365拍摄计划，希望坚持到老。

## 陪诊项目
* 缘于父母生小病，他们是在搞不懂医院的设置，总是请假陪诊。也看到有远离家乡的朋友，无法膝下承欢、嘘寒问暖。就曾经想过，如果能有机构，帮我带老人看病有多好。
* 2015年，也认识了朝阳基督堂的手语翻译张雪琴，她们在努力推动带残疾人去医院看病的项目，我个人非常支持。

## BP的BP
* 一个奇怪的想法是，我们可以创建一个连接创业者、投资人的网站。
* 创业者可以把自己的想法做成BP放到网站上面；
* 经过认证的投资人，可以足不出户观看BP，从而挑选项目；

`灿灿`
苏敏威武，一下子就想出这些好的点子，好想知道，这些中你最喜欢哪一个的创意，又最喜欢实施哪一个bp？

**Comment by dragon888code** [comment]
@sumin1123 ，我是做新媒体的，我也有记录癖，我一直用视频记录自己的想法，有些能分享的我就在公众号发表，[昨天我公众号的视频](https://mp.weixin.qq.com/s/ADPwOehmAbsgesCxoejAtg)；

虽然现在能做出片，但还没形成视频风格。

国外现在把能够一个人制作精良视频内容的人叫做——“独立制作人（和独立音乐人一样），本质上就是一个人可以把想法变成精美的视频内容。
那就是我的方向，
**我希望发挥我的所长我能和大家一起合作完成最后的BP**

`灿灿`
视频大师，未来的独立制作人，我们的故事展现环节要多拜托你喽。有时间可以给我们讲讲，如何用镜头讲故事。

**Comment by perhapslove** [comment]
# 区块链技术培训项目

区块链将是下一代互联网，与之相应的创业会越来越火，区块链技术人才一将难求。目前涉足区块链技术培训的项目相当少，国内目前只看到“渡鸦区块链”一家。区块链周边产业目前都集中在投资、工具及信息服务三大块。
`灿灿`
echo的想法很落地呢，有个疑问，这个没有体现故事层面思维，后期想要如何把一个bp的故事展现出来呢，欢迎回答。

**Comment by iamzhuoxuan** [comment]
0. 现代人解压工具

 —— 现代人压力过大（尤其是都市人），想做款产品，帮助现代人解压。具体什么样，还没有想到。
放大一些：可以扩大到心理领域，做一个心理健康产品。

> 最近发生很多事，丧到爆炸....我们能做些什么吗？产品形态我没想到，看你们有什么想法？

1. 中产阶级焦虑 —— 房价、物价、下一代教育。
2. 快速城市化过程中被当作炮灰的人.... 我们能做些什么。

Ps. 一眼看去，发现大家都在讲一些很阳光的故事，想反其道而行，讲一些不一样的故事。《很久很久以前》这本书提到有 12 种原则 —— 创造者、照顾者、统治者、弄臣、凡夫俗子、情人、英雄、亡命之徒、魔法师、天真者、探索家、智者。我们可以试一些不一样的故事：亡命之徒、魔法师这些 ；）

Pps. 我认识一个有意思的人，到时候我们确定方向，我让他帮我们参谋参谋。

**Comment by suncan0101** [comment]
产品方面具体没想好，想从人性角度出发，来一个看起来世界丧一些，但是我们本身峰回路转的东西，还在整理自己的思绪，其实根卓璇说的类似，讲不一样的故事。

**Comment by suncan0101** [comment]
## 知识普及平台（魔法师思维，改变世界）
昨天单位请消防局刘队长来给我们普及消防知识，纠正了我们对湿毛巾捂住口鼻，在卫生间等待救援，用湿棉被扑灭火险的错误认知，惊现国人对消防自救知识的匮乏。

听到一个真实案例，有一老爷子心肌梗塞倒在地上，一群老年人围着他，打110，注意是110，而不是120，带了半个小时，警察来了，重新叫了120，这就是我们身边的群众医务救援。

如果真有这样的平台，会有人真的关心吗？我们习惯了随大流，认为这些倒霉的事情不会波及到自身，刘队长说，大多数人对家庭消防设备了解甚少，感觉那些火灾都是别人家的事，没错，如果是自己家的事情，也许见到一次，就没有机会告诉别人你见到了。

**Comment by suncan0101** [comment]
关于生命、生存的问题和故事更能吸引人，素材易得，好讲，容易感染到人。给大家分享一个公益广告：深夜，酒吧里走出一个女人，四处暗黑，走到停车场她摁下车钥匙，灯光亮起，是一个手术室的景象亮了，一群手术台周边的医生看向她；另一个男人也是摁下车钥匙，灯光亮起，是一个法庭的景象亮了，法官和陪审团及律师回头看他。后来两个人把车熄灭，走着返了回去，屏幕亮起，喝酒不开车。

**Comment by suncan0101** [comment]
非常大的社会问题，人们关注，但是解决起来并非容易的，如果从表面看结果是消除大家的焦虑，实质应该需要深挖解决问题的方法，如果能想到解决途径，那就厉害了，看看实施强度如何，能否实现@iamzhuoxuan。

**Comment by iamzhuoxuan** [comment]
171202 五道口线下聚，大家票选出偏好的项目：

@sumin1123 知识普及平台（魔法师思维，改变世界）> @perhapslove 葡萄酒  > @sumin1123  陪诊项目 

接下来将寻求更多反馈，确定唯一项目，讨论 Issue 待  @suncan0101 补充

本 Issue 完美 CLOSE
