### ISSUE TITLE
项目发起人完善项目说明

### ISSUE THREAD

**Issue by suncan0101** [iamzhuoxuan/WriterBP#3]
# 项目发起人完善项目说明
## 项目说明内容
请陪诊项目、红酒项目、全民科普项目发起人完善各项目说明，以配合后期项目评定及项目公示工作，同时理清思路确定框架。具体可参照[BP 实操指南](https://github.com/AIWriter/Writer005/wiki/HBPractice)和[结业项目公示](https://github.com/AIWriter/Writer005/issues/162)。
## 回复时间
各位小伙伴@sumin @echo @suncan0101 请将项目说明于171205之前回复在本issue下。

**Comment by sumin1123** [comment]
# 请陪诊项目

医院楼上楼下，年迈的父母跑不动；
挂号建卡缴费，生病的家人理不清；
出差在外孩子生病，爱人一个人搞不定；
有时候只是感冒开药的小事情，还需请假一天；

如果有可信赖的机构，可以帮你带父母看病，帮你把医嘱记下转述给你；可以帮你的爱人打个下手；
就可以不必请假，安心工作；

**Comment by suncan0101** [comment]
## 守护者种子计划
你的很多生存知识只是道听途说
你信仰生死自有天命
你把灾难当成一个新闻、一串数据、一次次募捐

你爱家人
你保护家人
你除了一颗赤诚之心再无他物

知识就在那里无人问津
工具就在那里无人碰触
生命就在那里毫无保护

是原始地活
还是自主而生
你的手里握着选择权
我的双手已经将秘籍呈给你

你需要认识灾害
你更需要躲避灾害

你需要一个守护者
你可以成为一个守护者
请将守护者的种子埋下

我是种子
等你来

**Comment by iamzhuoxuan** [comment]
@sumin1123 @suncan0101 哇，你们直接用用认知写作学来写啦！我建议同时还要有一个正常介绍版，介绍一下产品、服务，方便他人更直观了解项目、提建议。
`灿灿`
谢谢@iamzhuoxuan的建议，我用项目公示的格式重写了一版，对于最终的产品是一个知识承载的一个app，还是一个体验馆，还是一个系列的组合，有些困惑。

**Comment by suncan0101** [comment]
## 守护者种子计划

### 项目概述

- 团队项目协作仓库地址：
[守护者种子计划](https://github.com/iamzhuoxuan/WriterBP/issues)
- 项目简介 ：
家人，是你最初和最后的守候，你努力工作、拼命挣钱，只为他们有一个舒适的生活环境。
大自然，是你和家人放松自我，获取更多幸福的空间，你抛下工作上的一切，挤出时间，带他们一起享受生命中的天伦之乐。
溪边，孩子和泥土玩游戏，爸妈坐在摇椅上闭目养神，你和爱人享受生活的静谧。孩子起身来请你看魔术：溪水变浑，你和他慢慢欣赏，等待你们的野兽慢慢靠近，你们只是享受这表面的平静······
水和火，景观与灾害，守护及知识，学校里有诗意的描述，单位中有种种渴望，身体里一颗跳动的心没有知识的武装，遇到灾害，你茫然中无力守护生命，那些生存知识，被忙碌的生活追赶着，没有时间和你相遇。
- 项目执行计划
全民科普防灾知识，不只是一个政府的宣传，不只是一个备用方案，不只是一个躺在手机里的海量自救信息；和家人一起学习防灾知识，带家人到防灾体验馆，为家人筑起一份知识守护，一切爱才会继续存在。
推进全民对生存环境的认识，促进你对自救知识的重视，简约信息呈现，优化传播途径，是我们一直的追求，守护者种子，只为你而种下。

**Comment by iamzhuoxuan** [comment]
最终选定 防灾馆 
issue 过时 close
