### ISSUE TITLE
项目评定标准

### ISSUE THREAD

**Issue by suncan0101** [iamzhuoxuan/WriterBP#4]
# 项目评定标准

## 背景、目标

~ 将拿着昨晚票选出来的 3 个项目，需带着问题去请教更多组外教练、同学、朋友的意见，获得更多反馈，确定唯一项目。

## 方案

~ 灿灿起草的方案

四项基本遵循：深挖人性+讲好故事+呈现美感+达到效果。

- 深挖人性
    - 项目牵涉的人性是否容易挖掘？
    - 是否可以深挖到底层？
    - 是否可以通过明线和暗线深刻表达？
    - 是否能够历经时间而不褪色，历经社会变迁依然产生影响？
- 讲好故事
    - 项目是否容易确定一个精彩的故事？
    - 故事是否深抓人们的心灵产生长远影响？
- 呈现美感
    - 能否通过视频或者图画和声音呈现故事的内核？
    - 素材的获取是否容易？
    - 故事是不是容易呈现一个很美的效果？
- 达到效果
    - 项目能否打动精英群体（老阳和教练团）？
    - 能否具有后期实现商业价值的导向？
    - 能否将人类对于商业推销的抗拒感降到最低？

## 行动

请大家在周三前 171206 18:00 前回复你的意见 —— 基于上述方案增补，或回复你的方案。届时将制成表单或问题清单，去请教他人。

**Comment by iamzhuoxuan** [comment]
我的问题比较简单 —— 

如果懂写作课的师友：

- 第 1 遍看完，你觉得哪个项目更吸引你？
- 是否能从逻辑、文采、故事 3 个角度提供一些建议。
- 哪一个未来更具有商业潜力。

不懂写作课的朋友：

- 第 1 遍看完，你觉得哪个项目更吸引你？
- 介绍目的。。你能帮我编一个故事？

**Comment by iamzhuoxuan** [comment]
issue 过时 close
